name = "Modrinth Cobblemon"
author = "cameron"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35359b43e0f8bb37263c2a64020d7f36365a1d3b131e4c38146ea0474c7ada7e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
