name = "Modrinth Cobblemon"
author = "cameron"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b11efd68aa3f26b070e590808a4e49980216ae3d174419b92952c6c4110c4fe"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
