name = "Modrinth Cobblemon"
author = "cameron"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d173fd3be983ac5f909b051f7cc2f93272f0ae22ef3dc397daf52bf09fd8d3e2"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
