name = "Cobblemon 2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "039e3453eb283a0ce4d1682ffb4e25e230e9ec903a41ae5cdd340cd12fcad340"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
